### PR TITLE
tpo's

### PR DESCRIPTION
**Pull request by robbyt**
looks like an interesting design so far :+1:

### CODE REVIEW

**Comment by bodepd** [comment]
sorry I missed this, the last thing I was expecting was a patch :) I'm feeling a bit too lazy to rebase atm. I may fix these separately and close this.

**Comment by robbyt** [comment]
No big deal-
Trivial documentation Pull Requests are my way of just saying "hi"

**Comment by bodepd** [comment]
@robbyt hi right back at ya :)

**Comment by bodepd** [comment]
@robbyt I have some newer docs that are way better:

```
https://github.com/CiscoSystems/openstack-installer/blob/master/data/README.md
```

**Pull request closed without merging**
